#使网关能够联系上nacos,并实现服务注册
server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848    #nacos地址
    gateway:
      routes:
        - id: user-sercive        #路由标示，必须唯一
          url: lb://userservice   #路由的目标地址
          predicate: #路由断言，判断请求是否符合规则
            - Path=/user/**  #路径断言，判断路径是否是以/user开头，如果是则符合
        - id: order-sercive        #路由标示，必须唯一
            url: lb://orderservice   #路由的目标地址,lb：loadBalance
            predicate: #路由断言，判断请求是否符合规则
              - Path=/order/**  #路径断言，判断路径是否是以/order开头，如果是则符合


